#pragma once

#define CELL_HEIGHT 1
#define CELL_WIDTH 2

#define N_ROWS_GAME_GRID 15
#define N_COLS_GAME_GRID 15

#define INITIAL_SNAKE_SIZE 4

#define SNAKE_GAME_MOVEMENT_DELAY_MS 100 
#define SNAKE_DEATH_ANIMATION_DELAY_MS 70

#define SNAKE_SIZE_MAIN_MENU 10
#define SNAKE_MAIN_MENU_ANIMATION_DELAY_MS 100
#define MAIN_MENU_SELECTION_BLINK_DELAY_MS 300

#define TITLE_Y_MAIN_MENU 4
#define PLAY_Y_MAIN_MENU 7
#define HELP_Y_MAIN_MENU 9
#define QUIT_Y_MAIN_MENU 11
#define SCORE_Y_MAIN_MENU 13

#define POPUP_ANIMATION_DELAY_MS 50
#define POPUP_BLINK_DELAY_MS 300
#define POPUP_SECONDS_REMAINING 20
#define POPUP_TITLE_BAR_SIZE 3
